apiVersion: v1
kind: List
items:
- kind: Deployment
  apiVersion: apps/v1
  metadata:
    name: fastapi-jaeger-deployment
    labels:
      app: fastapi
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: fastapi
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: fastapi
      spec:
        containers:
          - name: fastapi
            image: "fastapi-jaeger-example:latest"
            ports:
              - containerPort: 8000
                protocol: TCP
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            imagePullPolicy: Never
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxUnavailable: 25%
        maxSurge: 25%
    revisionHistoryLimit: 10
    progressDeadlineSeconds: 600
- apiVersion: v1
  kind: Service
  metadata:
    name: fastapi-jaeger-app
    labels:
      app: fastapi
  spec:
    ports:
    - name: fastapi-jaeger-app
      port: 8000
      nodePort: 30390
      protocol: TCP
      targetPort: 8000
    selector:
      app: fastapi
    type: NodePort
